Version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  
 Jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.5-node
    steps:
    -checkout
    -ruby/install-deps
    -ruby/rspec-test
    
Workflows:
  build_and_test:
    jobs:
      -build
